baseurl = "/"
languageCode = "en-us"
title = "Diarmuid Lloyd"
theme = "hugo-ivy"
googleAnalytics = ""
disqusShortname = ""
preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"
uglyURLs = false

[permalinks]
    post = "/:slug/"
    note = "/note/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "About"
    url = "/about"
    weight = 2
[[menu.main]]
    name = "Posts"
    url = "/post"
    weight = 3
[[menu.main]]
    name = "Tags"
    url = "/tags"
    weight = 5
 [[menu.main]]
    name = "Categories"
    url = "/categories"
    weight = 6   
[[menu.main]]
    name = "Contact"
    url = "/contact"
    weight = 7
    
[params]
    description = "witterings • R • data visualisation • everything else"
    footer = "Powered by [Hugo](https://gohugo.io/), [blogdown](https://github.com/rstudio/blogdown) and [the Ivy theme](https://github.com/yihui/hugo-ivy)"
    twitterImage = "/assets/summer-card.png"
    logo = "https://raw.githubusercontent.com/rstudio/hex-stickers/master/PNG/blogdown.png"
    
  highlightjsVersion = "9.12.0"
  highlightjsCDN = "//cdn.bootcss.com"
  highlightjsLang = ["r", "yaml", "tex"]
  highlightjsTheme = "github"


[blackfriday]
  hrefTargetBlank = true
